EcommerceApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('ecomm.urls')),
    path('', include('authentication.urls')),

    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomm/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('cart/', views.cart, name = 'cart'),
    path('product/<int:product_id>', views.product, name = 'product'),
    path('profile/', views.profile, name = 'profile'),
    path('wishlist/', views.wishlist, name = 'wishlist'),
    path('searched/', views.search, name = 'search'),
    path('checkout/', views.checkout, name = 'checkout'),
    path('add-to-cart/', views.updateCart, name = 'add-to-cart'),
    path('add-to-wish/', views.updateWishList, name = 'add-to-wish'),
    path('add-to-history/', views.recentlyViewed, name = 'add-to-history'),
]

ecomm/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.fields import BooleanField, DateTimeField
from django.db.models.fields.related import ForeignKey

# Create your models here.

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=CASCADE)
    firstName = models.CharField(max_length=50, null=True,blank=True)
    lastName = models.CharField(max_length=50, null=True,blank=True)
    email = models.EmailField(null=True,blank=True)
    profile = models.ImageField(default='user.png',null=True)
    phone = models.CharField(max_length=11, null=True)
    
    def __str__(self):
        return self.user.username

class Brand(models.Model):
    title = models.TextField(max_length=12, blank=False, null=True)
    logo = models.ImageField(null=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    
    title = models.CharField(max_length=50, blank=True)
    discount_price = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank = True)
    current_price = models.DecimalField(max_digits=20, decimal_places=2, null=True)
    image = models.ImageField(blank=False)
    ingredients = models.TextField()
    description = models.TextField()
    available = models.IntegerField()

    def __str__(self):
        return self.title

    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    @property
    def colortitle(self):
        color = self.color_set.all()
        return color

class Color(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    product = models.ForeignKey(Product, null=True, on_delete=CASCADE)

    def __str__(self):
        return self.product.title + ' in ' + self.title

class Productmedia(models.Model):
    product = models.ForeignKey(Product, on_delete=CASCADE, null=True)
    image = models.ImageField(blank=False)

    @property
    def imageUrl(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    def __str__(self):
        return self.product.title


class Wishlist(models.Model):
    customer = models.ForeignKey(Customer, on_delete=CASCADE)

    def __str__(self):
       return str(self.customer) + "'s" +' order'

class Wishitem(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=CASCADE)
    wishlist = models.ForeignKey(Wishlist, null=True, on_delete=CASCADE)

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=CASCADE, null=True)
    
    @property
    def cartTotal(self):
       cartItems = self.cartitem_set.all()
       total = sum([cartItem.itemTotal for cartItem in cartItems])
       return total
    
    @property
    def cartQuan(self):
        cartquan = self.cartitem_set.all()
        total = sum(quan.quantity for quan in cartquan)
        return total

    def __str__(self):
        return str(self.customer) + "'s" +' order'


class CartItem(models.Model):
   cart = models.ForeignKey(Cart, on_delete=CASCADE, null=True)
   product = models.ForeignKey(Product, null=True, on_delete=CASCADE)
   quantity = models.PositiveIntegerField(default=1, blank= False)


   def __str__(self):
        return self.product.title

   @property
   def itemTotal(self):
       total = self.product.current_price * self.quantity
       return total

class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=CASCADE, null=True)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=CASCADE, null=True)
    cartitem = models.ManyToManyField(CartItem)

    def __str__(self):
        return self.cartitem.product.title

class History(models.Model):
    customer = models.ForeignKey(Customer, on_delete=CASCADE, null=True)

    product = models.ForeignKey(Product, null=True, on_delete=CASCADE)

    

'''class Shipping(models.Model):
    customer = models.ManyToManyField(null=True)
    country = models.CharField(max_length=100, null = True)
    state = models.CharField(max_length=100, null = True)
    city = models.CharField(max_length=100, null = True)
    zipcode = models.IntegerField(max_length=100, null = True)
    address = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.address'''

templates/cart.html
{% extends 'index.html' %}
{% load static %}
{% block content %}

{% include 'navbar.html' %}

{% if cartItems %}

   <div id="cart-outer-wrapper">
      <div id="cart-wrapper">
         <table width='55%'>
               <tr id='row1'>
                   <td id='row1-content' colspan='3'>ITEMS({{cart.cartQuan}})</td>
      
               </tr>
               {% for cartItem in cartItems %}
      
               <tr class='row2' id='row-row-{{cartItem.product.id}}' data-product={{cartItem.product.id}} >
                   <td width='20%'>
      
                       <img class='table-img' src='{{cartItem.product.imageUrl}}'>
                   </td>
                   <td class='row2col2' valign='top'>
                     <p class='td1'>{{cartItem.product.title}}</p>
      
                     <div class='item-wrapper' id="item-price-wrapper-{{cartItem.product.id}}">
                        <p id='th1-{{cartItem.product.id}}'><i class="fas fa-dollar-sign"></i>{{cartItem.itemTotal}}</p>
                     </div>
      
      
                     <p class='td2'> Qty:
                        <i data-action='add' data-product={{cartItem.product.id}} id='add-{{cartItem.product.id}}'class="fas fa-plus updatecart"></i>
                        <span id="product-quantity-wrapper-{{cartItem.product.id}}" >
                           <span id="product-quantity-{{cartItem.product.id}}">{{cartItem.quantity}}</span>
                        </span>
      
                        <i data-product={{cartItem.product.id}} data-action='remove' id='remove-{{cartItem.product.id}}' class="fas fa-minus updatecart"></i></p>
      
                   </td>
      
                   <td valign='top' align='right'>
                     <a data-product={{cartItem.product.id}} data-action='delete' id='delete-{{cartItem.product.id}}'class="updatecart delete"> remove</a>
                   </td>
               </tr>
               {% endfor %}
         </table>
      
      
      
         <div class="checkbox-wrapper" id='checkbox-wrap'>
            <div class="checkout-title">
               ORDER SUMMARY
            </div>
            <div class="checkout-content">
               <div class="checkout-content-1">
                 <p>SUBTOTAL</p>
                 <p>DELIVERY</p>
               </div>
               <div id="checkout-content-2">
                 <div id="checkout-content-2-content">
                    <p>NGN{{cart.cartTotal}}</p>
                    <p>FREE</p>
                 </div>
               </div>
            </div>
            <div class="checkout">
               <a role='button' href='{% url "checkout" %}' class="btn btn-success checkout-button" aria-pressed="true">CHECKOUT
               </a>
            </div>
         </div>
        
      </div>
      
      {% else %}
         <div class='icon-wrapper' id='icon-wrap'>
            <i class="far fa-frown fa-9x center"></i>
            <p>
               Oops, There seems to be nothing in your cart
            </p>
            <a role='button' href='{% url "index" %}'class="btn btn-dark" aria-pressed="true">
               &larr;Start Shopping
            </a>
         </div>
      
      {% endif %}
   </div>

{% include 'navigation.html'%}

{% endblock %}

templates/checkout.html
{% extends 'index.html' %}
{% load static%}
{% block content %}

<div id="checkout-wrapper">
    <script src="https://www.paypal.com/sdk/js?client-id=AQqfIAEcQMKP40_9J8fperGi3-HgpRqGV3_gjAcc9eZxJ5Ugm1-zAYSyVmx6Jq0blVhj5TF1ruxgiNaT&currency=USD"></script>
    
    
        <!-- Set up a container element for the button -->
    
        <div id="paypal-button-container"></div>
    
    
        <script>
    
          paypal.Buttons({
    
    
            // Sets up the transaction when a payment button is clicked
    
            createOrder: function(data, actions) {
    
              return actions.order.create({
    
                purchase_units: [{
    
                  amount: {
    
                    value: '77.44' // Can reference variables or functions. Example: `value: document.getElementById('...').value`
    
                  }
    
                }]
    
              });
    
            },
    
    
            // Finalize the transaction after payer approval
    
            onApprove: function(data, actions) {
    
              return actions.order.capture().then(function(orderData) {
    
                // Successful capture! For dev/demo purposes:
    
                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
    
                    var transaction = orderData.purchase_units[0].payments.captures[0];
    
                    alert('Transaction '+ transaction.status + ': ' + transaction.id + '\n\nSee console for all available details');
    
    
                // When ready to go live, remove the alert and show a success message within this page. For example:
    
                // var element = document.getElementById('paypal-button-container');
    
                // element.innerHTML = '';
    
                // element.innerHTML = '<h3>Thank you for your payment!</h3>';
    
                // Or go to another URL:  actions.redirect('thank_you.html');
    
              });
    
            }
    
          }).render('#paypal-button-container');
    
    
        </script>
    
       
            
    <div>
        <span>Order Summary</span>
        {% for cartitem in cartItems %}
        <div id='image-wrapper'>
            <img src="{{cartitem.product.imageUrl}}
                    " alt="">
            <div>
                <div>{{cartitem.product.title}}</div>
                <div>{{cartitem.product.price}}</div>
            </div>
        </div>
        
        {% endfor %}
        
    </div>
</div>


{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <link rel='stylesheet' type='text/css' href='{% static "css/style.css" %}'>

    <link rel='stylesheet' type='text/css' href='{% static "css/mediaquery.css" %}'>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ladi</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
      crossorigin="anonymous">

    <link rel="icon" href="{% static 'favicon.ico' %}">

    <link rel="stylesheet" href='https://use.fontawesome.com/releases/v5.15.4/css/all.css'>

    <script type='text/javascript'>
        var user = '{{request.user}}'

        function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  // Does this cookie string begin with the name we want?
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }

      const csrftoken = getCookie('csrftoken');



      function getCookie(name) {
            var cookieArr = document.cookie.split(';');

            for (var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split('=');
                
                if (name == cookiePair[0].trim()) {
                    return decodeURIComponent(cookiePair[1]);
                }
            }
        
        return null;
    }

    var cart = JSON.parse(getCookie('cart'));
    var wish = JSON.parse(getCookie('wish'));
    var userCart = JSON.parse(getCookie('userCart'));
    
    if(cart == undefined){
      cart = {}
      document.cookie = 'cart=' + JSON.stringify(cart) + ';domain=;path=/' + '; expires=' + new Date(9999, 8, 15).toUTCString()
    }

    if(wish == undefined){
      wish = []
      document.cookie = 'wish=' + JSON.stringify(wish) + ';domain=;path=/' + '; expires=' + new Date(9999, 8, 15).toUTCString()
    }

    if(userCart == undefined){
      userCart = []
      document.cookie = 'userCart=' + JSON.stringify(userCart) + ';domain=;path=/' + '; expires=' + new Date(9999, 8, 15).toUTCString()
    }

    </script>
</head>
<body>


    {% block content %}

    {% include 'navbar.html' %}

    <div class='wrapper'>
      {% for product in products %}
        <div class='content overlay'>
          <div class='heart-wrapper'>
            <div class="heart"><i data-product={{product.id}} data-action='add' class="far fa-heart icon updatewish"></i></div>
            <a href="{% url 'product' product_id=product.id%}"><img class='index-img products' data-action data-productid={{product.id}} src='{{product.imageUrl}}'></a>
          </div>
           <div class='title'>
            {{product.title}}
           </div>
           <div class='price'>
            <span><i class="fas fa-dollar-sign"></i>{{product.current_price}}</span>
            {% if product.discount_price %}
            <span class='discount'>${{product.discount_price}}</span>
            {% endif %}
           </div>
        </div>
        {% endfor %}
      </div>

    {% if page_obj %}
    <div id="recently-viewed-wrapper">
      <div id="view-title">
        <span>RECENTLY VIEWED</span> 
        <button data-action="clear" class='clear products'>CLEAR ALL</button>
        
      </div>
      
        <div id="recent-outer">
          <div id="recently-viewed">

            {% for history in page_obj %}
            <div id="recent-{{history.product.id}}">
              <div id="recently-viewed-{{history.product.id}}">

                <div class='hearted-wrapper'><i id='hearted' data-product={{a_history.product.id}} data-action='add' 
                class="updatewish far fa-heart"></i></div>

              <div class='x-wrapper'><ion-icon
                  data-productId={{history.product.id}}
                  id='ion-x'
                  data-action='remove' name='close-sharp' class="products"></ion-icon> </div>
                <img src="{{history.product.imageUrl}}" alt="">
              </div>
            </div>
            {% endfor %}
          </div>
        {% endif %}
        
        {% for page in paginator.page_range %}
        <a id='?page={{page}}' class='paginator' href="javascript:void(0)">{{page}}</a></div>
        {% endfor %}
    </div>
    
    
    <div class='index-footer-wrapper'>
      <div class='brand-title'>MAJOR BRANDS</div>
      <div class='index-footer'>
          {% for brand in brands %}
              <img src='{{brand.logo.url}}'>
          {% endfor %}
      </div>
    </div>

    {% include 'navigation.html'%}
      
    {% endblock %}
  
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>

    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
            crossorigin="anonymous"></script>

    <script type='text/javascript' src='{% static "js/cart.js" %}'></script>

    <script type='text/javascript' src='{% static "js/index.js" %}'></script>

    <script type='text/javascript' src='{% static "js/wishlist.js" %}'></script>

</body>
</html> 

templates/login.html
{% extends 'index.html' %}
{% load static%}
{% block content %}

<div class="authentication">
    <div class="auth-title">
        MYBLOG.NG
    </div>
    <div class="auth-header">
        <div class="login" data-login>
           LOG IN
        </div>
        <div class="register" data-register>
            REGISTER
        </div>
    </div>
    
    <div class="auth-content">
            <form action="" method="post" class='auth-form'>{% csrf_token %}
                <p>{{form.username}}</p>
                <p>{{form.password1}}</p>
                <p>{{form.password2}}</p>

                <button type='submit' name='submit' value="signup" class='btn btn-primary'>
                    SIGN UP
                </button>

                <div class="outer-auth" data-login=""><a href="javascript:void(0)">ALREADY HAVE AN ACCOUNT? LOGIN </a></div>

            </form>
            

            <form action="" method="post" class='login-form'>{% csrf_token %}
                <p><input name='username' type="text" class="user form-control"></p>
                <p><input name='password' type="password" class="password form-control"></p>

                <button type='submit' name='submit' value="login" class='btn btn-primary'>
                    LOG IN
                </button>

                <div class="outer-login"  data-register><a href="javascript:void(0)">DON'T HAVE AN ACCOUNT? REGISTER </a></div>
            </form>
            
        </div>

    <div class="login-footer">
        gfhfk
    </div>
</div>

{% endblock %}

templates/navbar.html
<nav class='nav-wrapper'> 
    <div class='navigation'>
      <div class='nav-left-links'>
        <i class="fas fa-home fa-2x navUrl" data-url ="{% url 'index' %}"></i>
        <i class="far fa-user fa-2x navUrl" data-url="{% url 'profile' %}"></i>
      </div>
        <div class='nav-title'>
      This my blog
        </div>
        <div class='nav-right-links'>
      <form action={% url 'search' %} method="POST">{% csrf_token %}
        <input type="search" name="search" id="searchBar">
      </form>
      
      <i class="fas fa-search fa-2x search"></i>
     
      
      <div class="icon-box">
        <i class="fas fa-shopping-cart fa-2x navUrl" data-url="{% url 'cart' %}"></i>
        <div id="cart-total-wrapper">
          {% if cart.cartQuan == 0 %}
            
          {% else %}
          <div id="cart-total">
            {{cart.cartQuan}}
          </div>
          {% endif %}
        </div>
      </div>
      
      <div class="icon-box">
        <i class="far fa-heart fa-2x navUrl" data-url="{% url 'wishlist' %}"></i>
          <div id='wish-total-wrapper'>
            {% if wishitem|length == 0 %}
            
            {% else %}
            <div id="wish-total">
              {{wishitem|length}}
            </div>
            {% endif %}
          </div>
      </div>
        </div>
    </div>
    <div class='nav-bottom'>
      GET 20% OFF YOUR FIRST ORDER<span>|</span><span class='off'>USE CODE</span> <span>NGMYBLOG</span>
    </div>
</nav>


templates/navigation.html
<nav class='bottom-nav-wrapper'> 
     <div class='bottom-nav-content'>
        <div>
          <div id="side-content-info">
            <div class='footer'>CONNECT WITH US</div>
            <p class='side-content'>
              <span class='side-title'>CUSTOMER CARE</span><br>
              <a href="tel:09054521389">+2349054521389</a><br>
              <a href="tel:09036455136">+2349036455136</a>
            </p>
            <p class='side-content content2'>
              <span class='side-title'>EMAIL</span><br>
              <a href="mailto:catabong89@gmail.com">catabong89@gmail.com</a>
            </p>
          </div>
          <div class='media-icons'>
              <i data-url='#' class='brand fab fa-facebook'></i>
                 <i data-url='#' class='brand fab fa-snapchat'></i>
                 <i data-url='#' class='brand fab fa-instagram'></i>
                 <i data-url='#' class='brand fab fa-twitter'></i>
          </div>
        </div>
        
          <div id='about'>
            <div class='footer'>ABOUT US</div>
           
              <div class='second-div'>
                <ul>
                  <li>
                    <a class='contact-us' href='#'>
                      Social impact
                    </a>
                  </li>
                  <li>
                    <a class='contact-us' href='#'>
                      Accessibility
                    </a>
                  </li>
                  <li>
                    <a class='contact-us' href='#'>
                      Feedback
                    </a>
                  </li>
                  <li>
                    <a class='contact-us'href='#'>
                       Why This Blog
                    </a>
                  </li>
                  <li>
                    <a class='contact-us'href='#'>
                      Style Experts
                    </a>
                  </li>
                  <li>
                    <a class='contact-us'href='#'>
                      Investors
                    </a>
                  </li>
                  <li>
                    <a class='contact-us' href='#'>
                      Careers
                    </a>
                  </li>
                  
                </ul>
              </div>
             
            
          </div>
        <div class='fourth-div'>
          <div class='footer'>INFORMATION</div>
          <ul>
            <li>
              <a class='contact-us' href='#'>
                Shipping and Delivery
              </a>
            </li>
            <li>
              <a class='contact-us' href='#'>
                Returns and Exchange
              </a>
            </li>
            <li>
              <a class='contact-us' href='#'>
                Track Your Order
              </a>
            </li>
            <li>
              <a class='contact-us'href='#'>
                Gift Cards
              </a>
            </li>
          </ul>
        </div>
        <div class='bottom-nav-img'> 
          <a href="#"><img class="footer-img " src="https://is4.revolveassets.com/images/up/2021/September/082721_FWxPromo_RWfooter_B.png"  alt="Shop FWRD.com,  redirects to FWRD.com"></a>
         </div>
    </div> 
  <div class='bottom-nav-bottom'>
    &#169;2021|myBlog
  </div>
</nav>

templates/product.html
{% extends 'index.html' %}
{% load static%}
{% block content %}

{% include 'navbar.html' %}

<div class="product-wrapper">
    <div class="product-side-content">
        <div class="product-side-img">
            <img data-media class='sider-img' src="{{product.imageUrl}}
            " alt="">
        </div>
        {% for product in product.productmedia_set.all %}
        <div class="product-side-img">
            <img data-media class='sider-img down-sider-img' src="{{product.imageUrl}}
            " alt="">
        </div>
        {% endfor %}
    </div>

    <div class="product-img-wrapper">
        <div data-slides>
            <img data-image src="{{product.imageUrl}}" alt="" class="product-img">
            {% for product in product.productmedia_set.all %}
            <img data-images src="{{product.imageUrl}}" alt="" class="product-img">
            {% endfor %}
        </div>

        <span data-angle='next' class="angle angle-right">
            &#10093
        </span>
        <span data-angle='prev' class="angle angle-left">
            &#10092
        </span>

        <div class="product-title">INGREDIENTS</div>
        <div>{{product.ingredients}}</div>
        <div class=" product-title">
            DESCRIPTION
        </div>
        <div>{{product.description}}</div>

    </div>
    <div class="product-content">
        <div>{{product.title}}</div>
        <div class='product-info'>
            <i class="fas fa-dollar-sign"></i>{{product.current_price}}
            {% if product.discount_price %}
            <span>NGN{{product.discount_price}}</span>
            {% endif %}
        </div>
        
        
        <div class="product-colors">
            <div class="color-title">
                COLOR:
            </div>
            
            <div>
                {% for color in colors %}
                <div>{{color.title}}</div>
                {% endfor %}
            </div>
        </div>
        
        <div class='product-info'> IN STOCK {{product.available}}</div>
        <div>
            <button data-product={{product.id}} data-action='productmove' class=" add-to-bag updatecart" aria-pressed="true">
                    ADD TO BAG
            </button>
             
            <button type="submit" class='buy-now'> BUY NOW</button>


        </div>
    </div>
</div>

{% include 'navigation.html' %}
{% endblock %}

templates/profile.html
{% extends 'index.html' %}
{% load static%}
{% block content %}

{% include 'navbar.html' %}

<div class="profile-container">
    {% if request.user.is_authenticated %}

          
              <div class="profile-wrapper profile-wrapper-1">
              
                <div class='profile-pic'>
                    <img src="{% static 'images/user.png'%}" alt="">
                    <p>
                        {{request.user.username|title}}
                    </p>
                </div>
              
                <div>
                    FIRST NAME
                </div>
                <div>
                   LAST NAME
                </div>
                <div>
                  EMAIL
                </div>
                <div>
                  PHONE NUMBER
                </div>
                <a href="javascript:void(0)" class='edit-profile'> +EDIT PROFILE</a>

                <a href="{% url 'signout'%}">EXIT</a>
                
              </div>
              <div class="profile-wrapper profile-wrapper-2">
                <form action="" method="post" class='profile-form'>
                    <div class='profile-pic'>
                        <img src="{{form.profile}}" alt="">
                        <p>
                            {{request.user.username|title}}
                        </p>
                    </div>
              
                    <div>
                        {{form.firstName}}
                    </div>
                    <div>
                       {{form.lastName}}
                    </div>
                    <div>
                     {{form.email}}
                    </div>
                    <div>
                      {{form.phone}}
                    </div>
                    <button class='btn btn-primary'>
                        save
                    </button>
              
                </form>
              </div>

          <div class="profile-info">
            <div>
                <div>ORDERS</div>
                      
                <div>COUPONS</div>
                      
                <div>SHIPPING DETAILS</div>
                 
            </div> 
          </div>

    
    {% else %}

    <div class='profile'>
        <h3>Welcome Guest User</h3>
    </div>

    {% endif %}

</div>


{% endblock %}

templates/wishlist.html
{% extends 'index.html' %}

{% load static%}

{% block content %}

{% include 'navbar.html' %}

{%if wishitems %}
<div id="|">
    <div id='wish-wrapper'>
        {% for wishitem in wishitems %}
        <div class='wish-content' id='wish-content-{{wishitem.product.id}}' data-dropdown-menu>
            <div class='trash-wrapper'><i data-product={{wishitem.product.id}} data-action='delete' class="fas fa-trash-alt updatewish"></i></div>
    
           <img class ='wish-img' src='{{wishitem.product.imageUrl}}'>
    
            <p>{{wishitem.product.title}}</p>
                 
                <div class="dropdown-info">
                    SELECT COLOUR
                </div>
    
                <div class="dropdown-info">
                    SELECT SIZE
                </div>
    
                <div class="dropdown-color" data-dropdown>
                    SELECT COLOUR
                </div>
    
                <div class="dropdown-size" data-dropdown>
                    SELECT SIZE
                </div>
    
    
            <button id='wish-cart' data-product={{wishitem.product.id}}  data-action='move' class="btn btn-dark updatecart">ADD TO CART</button>
        </div>
    
        {% endfor %}
    </div>
    
    {% else %}
    <div class='icon-wrapper'>
        <i class="far fa-frown fa-9x center"></i>
        <p>
           You have no items in your wishlist
        </p>
        <a role='button' href='{% url "index" %}'class="btn btn-dark" aria-pressed="true">
           &larr;Start Shopping
        </a>
     </div>
     {% endif %}
</div>

 {% include 'navigation.html'%}
{% endblock %}